version: '3.8'

services:
  polyrl:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: polyrl-main
    network_mode: host
    privileged: true
    user: "0"
    userns_mode: host
    cap_add:
      - IPC_LOCK
    gpus: all
    shm_size: 512g
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - ../:/workspace/polyrl
    working_dir: /workspace/polyrl
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    stdin_open: true
    tty: true
    command: /bin/bash
